variables:
   ACE_ROOT: $(Build.SourcesDirectory)\ACE
   TAO_ROOT: $(Build.SourcesDirectory)\TAO
   system.prefergit: true

resources:
- repo: self
  fetchDepth: 1

queue:
  name: Hosted VS2017
  timeoutInMinutes: 90
  demands:
  - Cmd
  - msbuild
  - visualstudio

steps:
- powershell: |
   '#include "ace/config-win32.h"' > $(Build.SourcesDirectory)\ACE\ace\config.h
  displayName: 'Create config.h file'

- powershell: |
   $client = new-object System.Net.WebClient
   $client.DownloadFile("http://strawberryperl.com/download/5.28.0.1/strawberry-perl-5.28.0.1-64bit.zip","strawberry-perl.zip");
  displayName: 'Download perl'

- task: ExtractFiles@1
  displayName: 'Extract perl'
  inputs:
    archiveFilePatterns: 'strawberry-perl.zip'
    destinationFolder: perl

- powershell: git clone --depth 1 git://github.com/DOCGroup/MPC.git $(Build.SourcesDirectory)\ACE\MPC
  displayName: 'git clone MPC'

- task: BatchScript@1
  displayName: 'Run script perl\perl\bin\perl'
  inputs:
    filename: 'perl\perl\bin\perl'
    arguments: 'ACE\bin\mwc.pl -type vs2017 TAO\TAO_ACE.mwc'
    modifyEnvironment: false

- task: BatchScript@1
  displayName: 'Run script perl\perl\bin\perl'
  inputs:
    filename: 'perl\perl\bin\perl'
    arguments: 'ACE\bin\mwc.pl -type vs2017 ACE\tests\tests.mwc'
    modifyEnvironment: false

- task: VSBuild@1
  displayName: 'Build solution TAO\TAO_ACE.sln'
  inputs:
    solution: 'TAO\TAO_ACE.sln'
    maximumCpuCount: true

- task: VSBuild@1
  displayName: 'Build solution ACE\tests\tests.sln'
  inputs:
    solution: 'ACE\tests\tests.sln'
    maximumCpuCount: true






